// <auto-generated />
namespace BiofuelSouth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CleanupGlossary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CleanupGlossary));
        
        string IMigrationMetadata.Id
        {
            get { return "201504251958328_CleanupGlossary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
