// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace BiofuelSouth.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddsStorageCost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddsStorageCost));
        
        string IMigrationMetadata.Id
        {
            get { return "201506181215131_AddsStorageCost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
